In [1]:
import numpy as np


In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:


np.ones((4, 5), dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.twos(5)  # it does not exist

AttributeError: module 'numpy' has no attribute 'twos'

In [15]:
np.array([[2,2,2,2],[2,2,2,2]])

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [19]:
arr=np.zeros((3,3,4))

In [20]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
arr.ndim

3

In [21]:
arr=np.zeros((1,3,3,4))

In [22]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [23]:
arr.ndim

4

In [28]:
a=np.zeros([2,3])

In [29]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
b=a+5

In [33]:
b

array([[5., 5., 5.],
       [5., 5., 5.]])

In [34]:
# in similiar way we can substract add and multiply

In [36]:
np.eye(3) # all the diagonal element is 1 else 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.empty((2,3))# anything random values

array([[5., 5., 5.],
       [5., 5., 5.]])

In [38]:
#random module

import random
random.choice((1,2,5))

2

In [39]:
random.choice("ajazahmad")

'z'

In [40]:
random.randrange(1,100)

26

In [41]:
random.random()

0.01433309921254522

In [42]:
list=[1,2,3,4,5]
random.shuffle(list)

In [43]:
random.shuffle(list)


In [44]:
list

[4, 5, 1, 3, 2]

In [45]:
random.uniform(7,14)

7.87601538634983

In [46]:
# random number related concept in numpy

In [47]:
np.random.random_sample()

0.42633689922112106

In [48]:
np.random.random_sample((5,6))

array([[0.3253496 , 0.53254161, 0.8997897 , 0.73817799, 0.22167622,
        0.57870978],
       [0.90659592, 0.09740853, 0.598552  , 0.93051385, 0.87494038,
        0.70256993],
       [0.35604456, 0.05495715, 0.41392939, 0.66609022, 0.98424712,
        0.58266048],
       [0.57934301, 0.98173139, 0.57264285, 0.29603835, 0.93701945,
        0.40520964],
       [0.33806166, 0.84455153, 0.63742115, 0.56755752, 0.53804666,
        0.19760314]])

In [49]:
np.random.random_sample((5))

array([0.6977739 , 0.88370033, 0.23887535, 0.90813221, 0.84046717])

In [50]:
np.random.rand(2,3)

array([[0.85987325, 0.17327389, 0.2966346 ],
       [0.40752607, 0.08084826, 0.1501323 ]])

In [52]:
np.random.randn(2,3)

array([[ 0.19234613, -0.21719321, -0.26493702],
       [-2.22786961,  1.45283489, -0.42833544]])

In [53]:
np.random.randint(1,5)

1

In [ ]:
np.random.randint(1,5, size=(3,4)) # here start from 1 and stop on 5-1

array([[3, 4, 2, 1],
       [2, 1, 1, 3],
       [3, 1, 1, 3]])

In [56]:
a=np.random.randint(1,5, size=(3,4))

In [57]:
a.ndim

2

In [59]:
a.size

12

reshaping of array

In [61]:
a.reshape(2,6)

array([[4, 3, 3, 1, 3, 2],
       [1, 1, 4, 3, 1, 1]])

In [63]:
a.size

12

In [64]:
# array size will never change

In [65]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 36 into shape (3,2)

In [ ]:
# in case if we do not know in reshape what should be the row or column count
# use -1 for rows or columns (any negative value)
arr.reshape(4,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
arr.reshape(4,-100)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
# same in case of coloums

arr.reshape(-4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [71]:
a

array([[4, 3, 3, 1],
       [3, 2, 1, 1],
       [4, 3, 1, 1]])

In [72]:
a.reshape(2,2,3)

array([[[4, 3, 3],
        [1, 3, 2]],

       [[1, 1, 4],
        [3, 1, 1]]])

In [75]:
at=a.reshape(1,2,2,3)

In [76]:
at.ndim

4

In [77]:
a.reshape(4,3,1)

array([[[4],
        [3],
        [3]],

       [[1],
        [3],
        [2]],

       [[1],
        [1],
        [4]],

       [[3],
        [1],
        [1]]])

In [79]:
# condition of array
ap=np.random.randint(1,10,(5,6))

In [80]:
ap.shape

(5, 6)

In [81]:
ap.ndim

2

In [82]:
ap>3

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False,  True],
       [ True, False,  True,  True, False, False],
       [ True,  True,  True,  True, False,  True]])

In [83]:
ap[ap>3]

array([6, 4, 7, 4, 4, 8, 9, 6, 7, 7, 9, 9, 8, 6, 8, 8, 9, 6, 4, 9, 5])

In [84]:
ap

array([[6, 4, 7, 4, 4, 8],
       [9, 6, 7, 7, 9, 9],
       [2, 3, 3, 1, 1, 8],
       [6, 3, 8, 8, 2, 3],
       [9, 6, 4, 9, 3, 5]])

In [85]:
# to access element in array

In [86]:
ap[0]

array([6, 4, 7, 4, 4, 8])

In [87]:
ap[1]

array([9, 6, 7, 7, 9, 9])

In [89]:
ap[1][3]

7

In [90]:
ap[2][1]

3

In [91]:
ap

array([[6, 4, 7, 4, 4, 8],
       [9, 6, 7, 7, 9, 9],
       [2, 3, 3, 1, 1, 8],
       [6, 3, 8, 8, 2, 3],
       [9, 6, 4, 9, 3, 5]])

In [92]:
# from zeroth row to 2nd row
ap[0:3]

array([[6, 4, 7, 4, 4, 8],
       [9, 6, 7, 7, 9, 9],
       [2, 3, 3, 1, 1, 8]])

In [93]:
# from zeroth row to 2nd row and i want oth column and 2nd column
ap[0:3, [0,2]]

array([[6, 7],
       [9, 7],
       [2, 3]])

In [95]:
# slicing on both row and column
ap 

array([[6, 4, 7, 4, 4, 8],
       [9, 6, 7, 7, 9, 9],
       [2, 3, 3, 1, 1, 8],
       [6, 3, 8, 8, 2, 3],
       [9, 6, 4, 9, 3, 5]])

In [98]:
ap[0:3, 1:3]

array([[4, 7],
       [6, 7],
       [3, 3]])

In [100]:
ap[2:4,[0,3]]

array([[2, 1],
       [6, 8]])

In [101]:
# mathimatical operation on two arrays

In [6]:
arr1=np.random.randint(1,2,(3,3))

In [9]:
arr2=np.random.randint(1,3,(3,3))

In [7]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
arr2

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [ ]:
arr1+arr2 # index wise add the value 

array([[2, 2, 2],
       [3, 2, 2],
       [2, 3, 2]])

In [107]:
arr1-arr2

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 0, -1,  0]])

In [ ]:
arr1*arr2 # it is index wise multiplication not matrix

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [109]:
arr1,arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [2, 1, 1],
        [1, 2, 1]]))

In [ ]:
arr1/arr2 # index wise division

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [1. , 0.5, 1. ]])

In [111]:
arr1/0

C:\Users\Ajaz Ahamad\AppData\Local\Temp\ipykernel_5832\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [112]:
# matrix multiplication
arr1 @ arr2

array([[4, 4, 3],
       [4, 4, 3],
       [4, 4, 3]])

In [113]:
np.dot(arr1,arr2)

array([[4, 4, 3],
       [4, 4, 3],
       [4, 4, 3]])

In [2]:
import numpy as np

In [3]:
# transpose : coverting row into column and column into roe

In [8]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
arr2

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [12]:
arr2.T

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])