In [1]:
import numpy as np

In [4]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))


In [5]:
arr1

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [6]:
arr2

array([[2, 1, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [ ]:
arr1.flatten()# return a cppy of the array collapsed into one dimension

array([1, 2, 1, 1, 2, 2, 2, 2, 1])

In [8]:
# expend Dimension
arr=np.array([1,2,3,4])

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr.ndim

1

In [ ]:
np.expand_dims(arr)# increase the dimension by one in the provided axis,o means rows and column means 1 

In [11]:
np.expand_dims(arr,axis=0)

array([[1, 2, 3, 4]])

In [12]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [13]:
a=np.zeros((3,4))

In [14]:
a


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.expand_dims(a,axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
np.expand_dims(a,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [17]:
a=np.array([[1],[2],[3]])

In [18]:
a

array([[1],
       [2],
       [3]])

In [ ]:
#squeezing the dimension by 1 dimension

In [20]:
np.squeeze(a)# remove axes of lengh onr from a 

array([1, 2, 3])

In [21]:
a

array([[1],
       [2],
       [3]])

In [22]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [23]:
a

array([[1],
       [2],
       [3]])

In [24]:
arr1

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [25]:
np.repeat(arr1,2)

array([1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1])

In [26]:
np.repeat(arr1,2, axis=0)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 2],
       [1, 2, 2],
       [2, 2, 1],
       [2, 2, 1]])

In [27]:
np.repeat(arr2,3, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [28]:
np.repeat(arr1,2, axis=1)

array([[1, 1, 2, 2, 1, 1],
       [1, 1, 2, 2, 2, 2],
       [2, 2, 2, 2, 1, 1]])

In [29]:
np.repeat(arr2,3, axis=1)

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]])

In [30]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(a,-1)  # shift places

array([[2],
       [3],
       [1]])

In [32]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [33]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [34]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [36]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [39]:
d=np.array([[1,7],[3,4],[5,6],[7,8]])

In [40]:
d

array([[1, 7],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
c+d

array([[ 2,  9],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [42]:
c*d

array([[ 1, 14],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [43]:
c>d

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [44]:
# operation on numpy string array

In [45]:
e=np.array(["ajaz","ahamad"])

In [46]:
e

array(['ajaz', 'ahamad'], dtype='<U6')

In [47]:
np.char.upper(e)

array(['AJAZ', 'AHAMAD'], dtype='<U6')

In [48]:
np.char.capitalize(e)

array(['Ajaz', 'Ahamad'], dtype='<U6')

In [49]:
# Mthematical function 

In [50]:
a

array([[1],
       [2],
       [3]])

In [51]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
np.sin(c)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825]])

In [53]:
np.cos(c)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003]])

In [54]:
np.tan(c)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128],
       [-3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146]])

In [55]:
np.log(c)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154]])

In [56]:
np.exp(c)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03]])

In [57]:
np.power(c,3)

array([[  1,   8],
       [ 27,  64],
       [125, 216],
       [343, 512]], dtype=int32)

In [58]:
np.max(c)

8

In [59]:
np.mean(a)

2.0

In [60]:
np.min(c)

1

In [61]:
np.std(c)

2.29128784747792

In [62]:
np.subtract(c,d)

array([[ 0, -5],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [63]:
np.sort(c)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
# sorting and  searching in numpy array

In [65]:
e=np.array([5,7,1,4,3])

In [66]:
e

array([5, 7, 1, 4, 3])

In [67]:
np.sort(e)

array([1, 3, 4, 5, 7])

In [68]:
f=np.array([5,7,1,4,3])

In [71]:
q=np.searchsorted(f,6)  # find the elements should be inserted to maintain order

In [72]:
q

5

In [73]:
e=np.array([5,7,1,4,0,0,0,0,3])

In [74]:
np.count_nonzero(e)

5

In [75]:
e>0

array([ True,  True,  True,  True, False, False, False, False,  True])

In [76]:
import numpy.matlib as nm

In [77]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# numpy linear algebra

In [ ]:
# we can not divide matrix by another matrix, we have inverse

In [ ]:
#  to solve the mathematical equation problem like this
# 7x+5.3y-3=18
#3x-5y+2z=8
#5X+3Y-7Z=0
a=np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [79]:
b=np.array([16,8,0])

In [80]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])