#numpy: Numerical python 


it was developed by travis oliphant in 2005

In [1]:
import numpy as np # as is alias

In [2]:
np.__version__

'1.25.0'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
# numpy stores the data in numpy array
# array is a container used to store data of same data type(homogenious)

In [ ]:
# why numpy: already we have list?
# because numpy is build in c, and compuattaionnin c is very fast then we use numpy
# due to array is is fast because it stores homogeneous data since it has contigous memory location

In [7]:
l=[1,5,6,4]
a=np.array(l)

In [8]:
type(a)

numpy.ndarray

In [9]:
l1=[1,4,4,5,6,"ajaz"] # numpy array is homogenious it means elments can be of any data int,float,string it does not matter

In [10]:
np.array(l1)

array(['1', '4', '4', '5', '6', 'ajaz'], dtype='<U11')

In [11]:
l1=[1,4,4,5,6,2.5]

In [12]:
np.array(l1)

array([1. , 4. , 4. , 5. , 6. , 2.5])

In [ ]:
a.ndim  # a has only rows

1

In [16]:
arr=np.array([[1,2,3],[4,5,6]])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [21]:
m=np.matrix([1,2,3,8,4,3]) # matrix is a specialized array of 2D

In [24]:
m

matrix([[1, 2, 3, 8, 4, 3]])

In [22]:
type(m)

numpy.matrix

In [23]:
m.ndim

2

In [25]:
# to understand the dimension ,se the no of opening and closing sqaure bracket

In [28]:
# WE CAN NOT MAKE 3D MATRIX
np.matrix([[[1,2],[5,40],[5,4]]])

ValueError: matrix must be 2-dimensional

In [30]:
#we can make 3D array
m=np.array([[[1,2],[5,40],[5,4]]])

In [31]:
type(m)

numpy.ndarray

In [32]:
m.ndim

3

In [33]:
# more ways to array

l=[2,4,6]
np.asarray(l)

array([2, 4, 6])

In [34]:
np.asanyarray(l)

array([2, 4, 6])

In [44]:
t=(1,5,6)
ta=np.array(t)

In [36]:
# accessing the elements of array
# we can access same as list
# we can also chnage the value of array

In [45]:
a=ta

In [46]:
a

array([1, 5, 6])

In [51]:
ta

array([5000,    5,    6])

In [42]:
# this is shallow copy
# change in one array will reflect in another one

In [50]:
ta[0]=5000

In [52]:
ta

array([5000,    5,    6])

In [53]:
a

array([5000,    5,    6])

In [54]:
b=ta.copy()

In [55]:
b

array([5000,    5,    6])

In [56]:
ta

array([5000,    5,    6])

In [57]:
b[0]=14000

In [58]:
b

array([14000,     5,     6])

deep copy : changing in one array will not reflect in another 

# multiple way to generate an array

In [ ]:

np.fromfunction(lambda i, j: i == j, (3, 3))


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [65]:

a=np.fromfunction(lambda i, j: i == j, (9, 9))


In [66]:
a

array([[ True, False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False,  True]])

In [67]:
a.ndim

2

In [68]:
a.shape

(9, 9)

In [69]:
a.size

81

In [70]:

np.fromfunction(lambda i, j: i*j, (3, 3)) # true as 1 and false as 0


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [71]:
for i in range(5):
    print(i)

0
1
2
3
4


In [72]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [73]:
(i for i in range(5))

<generator object <genexpr> at 0x0000016969E4FE60>

In [75]:
list((i for i in range (5)))

[0, 1, 2, 3, 4]

In [ ]:
np.linspace(1,10,20)  # give 20 number between 1 to 10

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])